// ================================================================
// FEES.JS — Monthly Fee Management System
// Default fee: PKR 2000 (configurable by admin)
// Auto-generates pending records every month-end for all students
// ================================================================

const Fees = (() => {

  // ---- Fee Settings ----
  function getSettings() {
    return DB.getObj('feeSettings', { defaultAmount: 2000, schoolName: 'Hira Baitul Hamd' });
  }
  function saveSettings(s) { DB.set('feeSettings', s); }

  // ---- Get current month string e.g. "2025-03" ----
  function currentMonth() { return new Date().toISOString().slice(0, 7); }
  function monthLabel(m) {
    if (!m) return '-';
    const [y, mo] = m.split('-');
    const names = ['', 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
    return `${names[parseInt(mo)]} ${y}`;
  }

  // ---- Auto-generate monthly fees for ALL students ----
  function generateMonthlyFees(month) {
    const students = DB.get('students');
    if (!students.length) { toast('No students found!', 'error'); return 0; }
    const settings = getSettings();
    let fees = DB.get('fees');
    let added = 0;
    students.forEach(s => {
      const exists = fees.find(f => f.studentId === s.id && f.month === month);
      if (!exists) {
        fees.push({
          id: Utils.genId(),
          studentId: s.id,
          month,
          amount: settings.defaultAmount,
          status: 'pending',
          createdAt: Date.now(),
          autoGenerated: true,
        });
        added++;
      }
    });
    DB.set('fees', fees);
    return added;
  }

  // ---- Check & auto-trigger if month-end (25th or later) ----
  function checkMonthEndTrigger() {
    const today = new Date();
    const settings = getSettings();
    const mon = currentMonth();
    if (today.getDate() >= 25 && settings.lastAutoGenMonth !== mon) {
      settings.lastAutoGenMonth = mon;
      saveSettings(settings);
      return true; // show notification to student
    }
    return false;
  }

  // ---- RENDER Admin Page ----
  function render() {
    const classes = DB.get('classes');
    const sel = document.getElementById('fee-class-select');
    if (sel) sel.innerHTML = `<option value="">All Classes</option>` + classes.map(c => `<option value="${c.name}">${c.name}</option>`).join('');

    // Render settings bar
    const settingsBar = document.getElementById('fee-settings-bar');
    if (settingsBar) {
      const s = getSettings();
      settingsBar.innerHTML = `
        <div class="card mb-3">
          <div class="card-body py-3">
            <div class="row g-3 align-items-end">
              <div class="col-md-3">
                <label class="form-label fw-bold">🏫 Default Monthly Fee (PKR)</label>
                <div class="input-group">
                  <span class="input-group-text">PKR</span>
                  <input type="number" id="fee-default-amount" class="form-control" value="${s.defaultAmount}" min="0" step="100">
                </div>
              </div>
              <div class="col-md-3">
                <button class="btn btn-primary w-100" onclick="Fees.updateDefaultAmount()">💾 Save Default Amount</button>
              </div>
              <div class="col-md-3">
                <label class="form-label fw-bold">📅 Generate Fees for Month</label>
                <input type="month" id="fee-gen-month" class="form-control" value="${currentMonth()}">
              </div>
              <div class="col-md-3">
                <button class="btn btn-warning w-100" onclick="Fees.generateForMonth()">⚡ Generate Monthly Fees</button>
              </div>
            </div>
          </div>
        </div>`;
    }

    renderTable();
    renderStats();
  }

  function updateDefaultAmount() {
    const val = parseFloat(document.getElementById('fee-default-amount').value);
    if (!val || val <= 0) { toast('Enter a valid amount.', 'error'); return; }
    const s = getSettings();
    s.defaultAmount = val;
    saveSettings(s);
    toast(`✅ Default fee set to PKR ${val.toLocaleString()}`);
  }

  function generateForMonth() {
    const month = document.getElementById('fee-gen-month').value;
    if (!month) { toast('Select a month!', 'error'); return; }
    const added = generateMonthlyFees(month);
    if (added === 0) toast(`Fees already generated for ${monthLabel(month)}!`, 'info');
    else toast(`✅ Generated ${added} fee records for ${monthLabel(month)}`);
    renderTable(); renderStats();
  }

  function renderStats() {
    const fees = DB.get('fees');
    const total = fees.reduce((s, f) => s + f.amount, 0);
    const paid = fees.filter(f => f.status === 'paid').reduce((s, f) => s + f.amount, 0);
    const pending = fees.filter(f => f.status === 'pending').reduce((s, f) => s + f.amount, 0);
    const set = (id, v) => { const el = document.getElementById(id); if (el) el.textContent = v; };
    set('fee-total', `PKR ${total.toLocaleString()}`);
    set('fee-paid', `PKR ${paid.toLocaleString()}`);
    set('fee-pending', `PKR ${pending.toLocaleString()}`);
  }

  function renderTable(filter = '') {
    let fees = DB.get('fees');
    const students = DB.get('students');
    if (filter) fees = fees.filter(f => {
      const s = students.find(st => st.id === f.studentId);
      return s?.cls === filter;
    });
    fees.sort((a, b) => b.month > a.month ? 1 : -1);
    const tbody = document.getElementById('fees-tbody');
    if (!tbody) return;
    if (!fees.length) {
      tbody.innerHTML = `<tr><td colspan="7"><div class="empty-state"><div class="empty-state-icon">💰</div><h5>No Fee Records</h5><p>Click "Generate Monthly Fees" to auto-create records for all students, or add manually.</p></div></td></tr>`;
      return;
    }
    tbody.innerHTML = fees.map((f, i) => {
      const s = students.find(st => st.id === f.studentId);
      const overdue = f.status === 'pending' && f.month < currentMonth();
      return `<tr${overdue ? ' class="table-danger"' : ''}>
        <td>${i + 1}</td>
        <td class="fw-semibold">${s?.name || '-'}</td>
        <td><span class="badge-class">${s?.cls || '-'} ${s?.section || ''}</span></td>
        <td>${monthLabel(f.month)}</td>
        <td class="fw-bold">PKR ${f.amount.toLocaleString()}</td>
        <td>
          <span style="background:${f.status === 'paid' ? 'var(--success-light)' : overdue ? 'rgba(239,68,68,.15)' : 'var(--danger-light)'};color:${f.status === 'paid' ? 'var(--success)' : overdue ? '#ef4444' : 'var(--danger)'};font-size:11px;font-weight:700;padding:3px 10px;border-radius:20px">
            ${f.status === 'paid' ? '✅ Paid' : overdue ? '🔴 Overdue' : '⏳ Pending'}
          </span>
        </td>
        <td>
          ${f.status === 'pending' ? `<button class="btn btn-sm btn-success btn-icon me-1" onclick="Fees.markPaid('${f.id}')" title="Mark Paid">✅</button>` : `<button class="btn btn-sm btn-outline-success btn-icon me-1" onclick="Reports.printFeeReceipt('${f.id}')" title="Print Receipt">🖨️</button>`}
          <button class="btn btn-sm btn-outline-primary btn-icon me-1" onclick="Fees.editAmount('${f.id}')" title="Edit Amount">✏️</button>
          <button class="btn btn-sm btn-outline-danger btn-icon" onclick="Fees.del('${f.id}')">🗑️</button>
        </td>
      </tr>`;
    }).join('');
  }

  function openAdd() {
    const students = DB.get('students');
    const sel = document.getElementById('fee-student-select');
    if (sel) sel.innerHTML = `<option value="">Select Student</option>` + students.map(s => `<option value="${s.id}">${s.name} — ${s.roll} (${s.cls})</option>`).join('');
    const amtEl = document.getElementById('fee-amount');
    if (amtEl) amtEl.value = getSettings().defaultAmount;
    const monEl = document.getElementById('fee-month');
    if (monEl) monEl.value = currentMonth();
    new bootstrap.Modal(document.getElementById('feeModal')).show();
  }

  function save() {
    const studentId = document.getElementById('fee-student-select').value;
    const month = document.getElementById('fee-month').value;
    const amount = parseFloat(document.getElementById('fee-amount').value);
    const status = document.getElementById('fee-status').value;
    if (!studentId || !month || !amount) { toast('All fields required.', 'error'); return; }
    const existing = DB.get('fees').find(f => f.studentId === studentId && f.month === month);
    if (existing) { toast('Fee record for this student & month already exists!', 'error'); return; }
    const fees = DB.get('fees');
    fees.push({ id: Utils.genId(), studentId, month, amount, status, createdAt: Date.now() });
    DB.set('fees', fees);
    bootstrap.Modal.getInstance(document.getElementById('feeModal'))?.hide();
    toast('Fee record added! 💰');
    renderTable(); renderStats();
  }

  function editAmount(id) {
    const fee = DB.get('fees').find(f => f.id === id);
    if (!fee) return;
    const newAmt = prompt(`Edit amount for ${monthLabel(fee.month)} (current: PKR ${fee.amount}):`, fee.amount);
    if (newAmt === null) return;
    const val = parseFloat(newAmt);
    if (!val || val <= 0) { toast('Invalid amount.', 'error'); return; }
    DB.set('fees', DB.get('fees').map(f => f.id === id ? { ...f, amount: val } : f));
    toast(`Amount updated to PKR ${val.toLocaleString()}! ✅`);
    renderTable(); renderStats();
  }

  function markPaid(id) {
    const fees = DB.get('fees').map(f => f.id === id ? { ...f, status: 'paid', paidAt: Date.now() } : f);
    DB.set('fees', fees);
    toast('Marked as Paid! ✅');
    renderTable(); renderStats();
  }

  function del(id) {
    confirmDialog('Delete this fee record?', () => {
      DB.set('fees', DB.get('fees').filter(f => f.id !== id));
      toast('Fee deleted.', 'info');
      renderTable(); renderStats();
    });
  }

  return {
    render, renderTable, renderStats,
    openAdd, save, markPaid, del,
    updateDefaultAmount, generateForMonth, generateMonthlyFees,
    getSettings, checkMonthEndTrigger,
    currentMonth, monthLabel,
  };
})();
